name: Build and Deploy
on:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
        working-directory: ./webapp
      - name: Build
        run: npm run build
        working-directory: ./webapp
        env:
          SASS_PATH: ./node_modules;./src
          REACT_APP_LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
          REACT_APP_LASTFM_API_PAGE_SIZE: ${{ secrets.LASTFM_API_PAGE_SIZE }}
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: ./webapp/dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
